### ISSUE TITLE
I read your work

### ISSUE THREAD

**Issue by kennychidikenny** [betascribbles/betascribbles#1]
Hi Firdaus,
I'm Chidi, I got accepted into **ALX Software Engineering Program.**
I read your [article ](https://medium.com/geekculture/how-i-tackle-my-projects-at-alx-holberton-school-610f3f5a6448). Thanks for putting that together. 
Please, which platform do you recommend for one to use in documenting his/her learning process?

**Comment by betascribbles** [comment]
Hi Chidi
Congratulations! Welcome to alx
Personally, I use a pen-paper diary. I journal every day and that's part of my learning documentation. I also post my work on Twitter. When I take part in **#100DaysOfCode** challenge, I keep a repo log like [this](https://github.com/betascribbles/100DaysOfCode)

Document in whatever way you feel is best for you. You may choose to record videos or keep an online diary, or tweet... feel free.

**Comment by kennychidikenny** [comment]
> Hi Chidi Congratulations! Welcome to alx Personally, I use a pen-paper diary. I journal every day and that's part of my learning documentation. I also post my work on Twitter. When I take part in **#100DaysOfCode** challenge, I keep a repo log like [this](https://github.com/betascribbles/100DaysOfCode)
> 
> Document in whatever way you feel is best for you. You may choose to record videos or keep an online diary, or tweet... feel free.

Thanks alot
